fitur1/urls.py
from django.conf.urls import url
from .views import *
#url for app
urlpatterns = [
    url(r'^$', index, name='index'),
    url(r'^login/', login, name='login' ),
    url(r'^logout/', logout, name='login' ),
]

fitur6/urls.py
from django.conf.urls import url
from .views import *
#url for app
urlpatterns = [
    url(r'^$', index, name='index'),
    url(r'^detail/(?P<kodeB>.*)/', detail, name='detail' ),
    url(r'^terima/(?P<no_urut>.*)/(?P<kode_beasiswa>.*)/(?P<npm>.*)/', terima, name='terima' ),
    url(r'^tolak/(?P<no_urut>.*)/(?P<kode_beasiswa>.*)/(?P<npm>.*)/', tolak, name='tolak' ),
]

projSIMBION/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from homepage.views import index as index_homepage
import homepage.urls as homepage
import fitur1.urls as fitur1
import fitur2.urls as fitur2
import fitur3.urls as fitur3
import fitur4.urls as fitur4
import fitur5.urls as fitur5
import fitur6.urls as fitur6

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^home/', include(homepage,namespace='homepage')),
    url(r'^$', index_homepage, name='index'),
    # url(r'^pendaftaranPaket/', include(fitur3,namespace='pendaftaranPaket')),
    # url(r'^tambahDariPaket/', include(fitur3,namespace='tambahDariPaket')),
    url(r'^auth/', include(fitur1,namespace='login')),
    url(r'^register/', include(fitur2,namespace='register')),
    url(r'^PaketBeasiswa/', include(fitur3,namespace='tambahDariPaket')),
    url(r'^infoBeasiswa/', include(fitur4,namespace='infoBeasiswa')),
    url(r'^mahasiswaDashboard/', include(fitur5,namespace='mahasiswaDashboard')),
    url(r'^donaturDashboard/', include(fitur6,namespace='donaturDashboard')),
]

fitur6/models.py
from django.db import models

# Create your models here.

fitur6/views.py
from django.shortcuts import render
from django.db import connection

# Create your views here.
response = {}
def index(request):
	cursor = connection.cursor()

	# dummy username buat sementara
	response['username'] = request.session['username']

	cursor.execute("SELECT role FROM pengguna WHERE username='" + response['username']+"'")
	response['role'] = cursor.fetchone()[0]

	cursor.execute("SELECT nomor_identitas, nama, email, no_telp FROM donatur WHERE username='" + response['username']+"'")
	profil = cursor.fetchone()

	response['nomor_identitas'] = profil[0]
	response['nama'] = profil[1]
	response['email'] = profil[2]
	response['no_telp'] = profil[3]

	cursor.execute(" SELECT distinct nama, tgl_tutup_pendaftaran, status, jumlah_pendaftar, kode FROM skema_beasiswa join skema_beasiswa_aktif on kode=kode_skema_beasiswa WHERE nomor_identitas_donatur='" + response['nomor_identitas']+"'")

	output = cursor.fetchall()
	response['arrBeasiswa'] = output

	return render(request, 'donaturDashboard.html', response)

def detail(request, kodeB):
	cursor = connection.cursor()
	response['username'] = request.session['username']

	cursor.execute(" SELECT distinct nama, deskripsi, kode FROM skema_beasiswa WHERE kode='" + kodeB+"'")
	response['dataBeasiswa'] = cursor.fetchone()

	cursor.execute("SELECT no_urut, nama, npm, waktu_daftar, status_terima FROM pendaftaran NATURAL JOIN mahasiswa WHERE kode_skema_beasiswa = '" + kodeB+"'")
	response['arrPendaftar'] = cursor.fetchall()


	return render(request, 'detailBeasiswa.html', response)

def terima(request, no_urut, kode_beasiswa, npm):
	cursor = connection.cursor()
	cursor.execute("UPDATE pendaftaran SET status_terima='DITERIMA' WHERE no_urut='" +no_urut+ "' AND kode_skema_beasiswa='" +kode_beasiswa+ "' AND npm='" +npm+ "'")

	return detail(request, kode_beasiswa)


def tolak(request, no_urut, kode_beasiswa, npm):
	cursor = connection.cursor()
	cursor.execute("UPDATE pendaftaran SET status_terima='DITOLAK' WHERE no_urut='" +no_urut+ "' AND kode_skema_beasiswa='" +kode_beasiswa+ "' AND npm='" +npm+ "'")

	return detail(request, kode_beasiswa)

fitur6/templates/detailBeasiswa.html
{% extends "base.html" %}
{% block content %}

<!DOCTYPE html>
<html>

<body>
  <div class="py-5" >
    <div class="container">
      <div class="row">
        <div class="col-md-12">
          <h1 class="my-3 text-primary">
            <b>Beasiswa {{dataBeasiswa.0}}</b>
          </h1>
        </div>
      </div>
      <div class="row">
        <div class="col-md-12">
          <p class="">{{dataBeasiswa.1}} </p>
        </div>
      </div>
    </div>
  </div>
  <div class="py-2">
    <div class="container">
      <div class="row">
        <div class="col-md-12">
          <h1 class="text-primary my-1">
            <b class="H2">Daftar Pendaftar</b>
          </h1>
        </div>
      </div>

      {% for pendaftar in arrPendaftar %}

      <div class="row my-2 py-1">
        <div class="d-flex col-md-12">
          <div class="d-flex">
            <div class="center-wrapper w-100 m-2" align="center">
              <p class="H1">&nbsp;No. {{pendaftar.0}}</p>
              <br> </div>
          </div>
          <a href="#" class="list-group-item list-group-item-action flex-column align-items-start">
            <div class="d-flex w-100 justify-content-between">
              <h5 class="mb-1">{{pendaftar.1}}</h5>
            </div>
            <p class="mb-1">NPM. {{pendaftar.2}}</p>
            <small class="text-muted">Waktu Daftar: {{pendaftar.3}}</small>
            <br>
            <small class="text-muted">Status Penerimaan: {{pendaftar.4}}</small>
          </a>
          <div class="d-flex">
            <div class="center-wrapper w-100 m-2" align="center">
              <a class="btn btn-secondary my-3" href="{% url 'donaturDashboard:terima' pendaftar.0 dataBeasiswa.2 pendaftar.2 %}">Terima</a>
              </div>
              <br>
          </div>
          <div class="d-flex">
            <div class="center-wrapper w-100 m-2" align="center">
              <a class="btn my-3 btn-primary" href="{% url 'donaturDashboard:tolak' pendaftar.0 dataBeasiswa.2 pendaftar.2 %}">Tolak</a>
              <br> </div>
          </div>
        </div>
      </div>

      {% endfor %}

  </div>
  <div class="py-5">
  </div>

<!--       <div class="row my-3">
        <div class="col-md-12">
          <ul class="pagination">
            <li class="page-item">
              <a class="page-link" href="#">
                <span>«</span>
                <span class="sr-only">Previous</span>
              </a>
            </li>
            <li class="page-item">
              <a class="page-link" href="#">1</a>
            </li>
            <li class="page-item">
              <a class="page-link" href="#">2</a>
            </li>
            <li class="page-item">
              <a class="page-link" href="#">3</a>
            </li>
            <li class="page-item">
              <a class="page-link" href="#">4</a>
            </li>
            <li class="page-item">
              <a class="page-link" href="#">
                <span>»</span>
                <span class="sr-only">Next</span>
              </a>
            </li>
          </ul>
        </div>
      </div>
    </div> -->

  </div>

</body>


</html>
{% endblock %}

fitur6/templates/donaturDashboard.html
{% extends "base.html" %}
{% block content %}

<!DOCTYPE html>
<html>

<body>
  <div class="py-5">
    <div class="container">
      <div class="row">
        <div class="col-md-4">
          <div class="col-md-12 p-4">
            <img class="img-fluid d-block rounded-circle mx-auto" src="http://globalmedicalco.com/photos/globalmedicalco/20/98173.jpg" width="200" height="200 200 400">
            <h3 class="text-center my-2">
              <b class="text-primary">{{ nama }}</b>
              <br>as {{ role }}</h3>
            <div class="row">
              <div class="col-md-12 my-1">
                <ul class="">
                  <li>Username : {{ username }}</li>
                  <li>Id donatur : {{ nomor_identitas }}</li>
                  <li>Email : {{ email }}</li>
                  <li>No Telepon : {{ no_telp }}</li>
                </ul>
              </div>
            </div>
            <div class="row my-1">
              <div class="col-md-12">
                <div class="center-wrapper my-1" align="center">
                  <a class="btn btn-secondary" href="/PaketBeasiswa/pendaftaranPaket/">Buat Paket Beasiswa Baru</a>
                </div>
              </div>
            </div>
            <div class="row my-1">
              <div class="col-md-12">
                <div class="center-wrapper my-1" align="center">
                  <a class="btn btn-secondary" href="/PaketBeasiswa/tambahDariPaket/"> Menambahkan Beasiswa dari Paket </a>
                </div>
              </div>
            </div>
          </div>
        </div>
        <div class="col-md-8">
          <h1 class="my-3 text-primary">
            <b>Beasiswa Anda</b>
          </h1>

          {% for beasiswa in arrBeasiswa %}

          <div class="row my-2 py-1">
            <div class="col-md-9">
              <a href="#" class="list-group-item list-group-item-action flex-column align-items-start">
                <div class="d-flex w-100 justify-content-between">
                  <h5 class="mb-1">Beasiswa {{ beasiswa.0 }}</h5>
                </div>
                <p class="mb-1">Waktu tutup {{ beasiswa.1 }}</p>
                {% if beasiswa.2 %}
                  <small class="text-muted">Penerimaan beasiswa telah berakhir</small>
                {% else %}
                  <small class="text-muted">Penerimaan beasiswa masih dibuka</small>
                {% endif %}
              </a>
            </div>
            <div class="col-md-3">
              <p class="my-1 text-center">
                Total pendaftar
                <b>{{ beasiswa.3 }}</b>
              </p>
              <div class="center-wrapper my-1" align="center">
                <a class="btn btn-secondary" href="{% url 'donaturDashboard:detail' beasiswa.4 %}">Set Penerima</a>
              </div>
            </div>
          </div>

          {% endfor %}

        </div>
      </div>
    </div>
  </div>
</body>

</html>
{% endblock %}